# Generated by Django 5.2.6 on 2025-09-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='O título', max_length=200)),
                ('media_type', models.CharField(choices=[('video', 'Vídeo'), ('image', 'Imagem')], max_length=5)),
                ('file', models.FileField(upload_to='display_media/')),
                ('duration_in_seconds', models.PositiveIntegerField(default=10, help_text='Apenas para imagens. Define por quantos segundos a imagem será exibida.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Define a ordem de exibição.')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
