# Generated by Django 5.2.6 on 2025-09-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoCycler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='displayitem',
            name='mute',
            field=models.BooleanField(default=True, help_text='Apenas para vídeos. Define se o vídeo será reproduzido sem som.'),
        ),
    ]
