services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - media_data:/app/media
      - db_data:/app/db/
    environment:
      - RUNNING_IN_DOCKER=true
    env_file:
      - .env
volumes:
  db_data:
  media_data:
